site_name: HCI-FACE
site_url: https://tbd.com/
repo_url: https://github.com/chrismbirmingham/hci-face
dev_addr: 127.0.0.2:8001
nav:
- Overview: index.md
- Frontend: frontend.md
- Backend: backend.md
- Modules: modules/
- Tutorials: tutorials/
- Troubleshooting: troubleshooting.md
- Backend Reference: reference/
watch:
- backend
theme: 
    name: material
    features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.sections
    - navigation.tracking
    - navigation.expand
    palette: 
        primary: green
        accent: light blue
plugins:
- mkdocstrings
- literate-nav:
    nav_file: SUMMARY.md
- search
- gen-files:
    scripts:
    - docs/gen_ref_pages.py

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
