site_name: HCI-FACE
site_url: https://tbd.com/
nav:
- Home: index.md
- Backend: backend.md
- Tutorials: tutorials/
- Reference: reference/
theme: 
    name: material
    features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.sections
    - navigation.tracking
    - navigation.expand
plugins:
- mkdocstrings
- literate-nav:
    nav_file: SUMMARY.md
- search
- gen-files:
    scripts:
    - docs/gen_ref_pages.py

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
